"""Regenerate exp/ENV.md from the live medical1 environment."""
import importlib
import platform
import subprocess
import sys
from pathlib import Path

EXP = Path(__file__).resolve().parents[2]
PY = sys.executable

PKGS = [
    "numpy", "scipy", "skimage", "sklearn", "cv2", "pandas", "statsmodels",
    "lightgbm", "networkx", "skan", "matplotlib", "seaborn", "tqdm", "yaml",
    "albumentations", "tifffile", "PIL", "imageio", "numba", "PVBM",
    "requests", "gdown",
]
DIST = {
    "skimage": "scikit-image", "sklearn": "scikit-learn",
    "cv2": "opencv-python-headless", "yaml": "PyYAML", "PIL": "pillow",
    "PVBM": "pvbm",
}


def ver(mod):
    try:
        m = importlib.import_module(mod)
    except Exception as e:
        return "IMPORT FAILED: %s" % e
    for a in ("__version__", "version", "VERSION"):
        v = getattr(m, a, None)
        if isinstance(v, str):
            return v
    try:
        from importlib.metadata import version
        return version(DIST.get(mod, mod))
    except Exception:
        return "(installed, version unknown)"


def main():
    import torch
    import torchvision

    lines = []
    A = lines.append
    A("# Environment — `medical1`\n")
    A("Generated by `exp/src/data/_write_env_md.py`.\n")
    A("## Use this interpreter\n")
    A("```")
    A(PY.replace("\\", "/"))
    A("```\n")
    A("`conda run -n medical1 ...` swallows stdout on this machine — call the")
    A("interpreter path above directly (or `conda activate medical1` in an")
    A("interactive shell).\n")
    A("## Core\n")
    A("| item | version |")
    A("|------|---------|")
    A("| OS | %s |" % (platform.platform(),))
    A("| Python | %s |" % sys.version.split()[0])
    A("| conda env prefix | `%s` |" % sys.prefix.replace("\\", "/"))
    A("| torch | %s |" % torch.__version__)
    A("| torchvision | %s |" % torchvision.__version__)
    A("| torch CUDA build | %s |" % torch.version.cuda)
    A("| cuDNN | %s |" % torch.backends.cudnn.version())
    A("| torch.cuda.is_available() | %s |" % torch.cuda.is_available())
    A("| torch.cuda.device_count() | %d |" % torch.cuda.device_count())
    for i in range(torch.cuda.device_count()):
        p = torch.cuda.get_device_properties(i)
        A("| GPU %d | %s, %.1f GB, sm_%d%d |"
          % (i, p.name, p.total_memory / 1024 ** 3, p.major, p.minor))
    A("")
    A("## Scientific stack\n")
    A("| import name | version |")
    A("|-------------|---------|")
    for m in PKGS:
        A("| `%s` | %s |" % (m, ver(m)))
    A("")
    A("## pip freeze\n")
    A("```")
    out = subprocess.run([PY, "-m", "pip", "freeze"],
                         capture_output=True, text=True).stdout
    A(out.strip())
    A("```")
    (EXP / "ENV.md").write_text("\n".join(lines), encoding="utf-8")
    print("wrote", EXP / "ENV.md", "(%d lines)" % len(lines))


if __name__ == "__main__":
    main()
