"""Render ``results/pivot/PROBE_REPORT_P4P5.md`` from the P4/P5 result CSVs.

Every table below is produced from a file on disk -- nothing is transcribed by
hand -- so the report and the CSVs cannot drift apart.

    python -m src.pivot.make_report_p4p5
"""
from __future__ import annotations

import io
import json
import os
import sys

import pandas as pd

from src.pivot.common import PIVOT_DIR

OUT = os.path.join(PIVOT_DIR, "PROBE_REPORT_P4P5.md")


def md(df: pd.DataFrame, cols=None, r=3) -> str:
    """Minimal GitHub-flavoured markdown table (no tabulate dependency)."""
    d = (df if cols is None else df[cols]).round(r)

    def cell(v):
        if v is None or (isinstance(v, float) and pd.isna(v)):
            return ""
        if isinstance(v, float):
            return ("%.{}f".format(r)) % v
        return str(v)

    head = "| " + " | ".join(str(c) for c in d.columns) + " |"
    sep = "|" + "|".join("---" for _ in d.columns) + "|"
    body = ["| " + " | ".join(cell(v) for v in row) + " |"
            for row in d.itertuples(index=False, name=None)]
    return "\n".join([head, sep] + body) + "\n"


def jload(p, default=None):
    if not os.path.exists(p):
        return default
    with open(p, encoding="utf-8") as f:
        return json.load(f)


def main(argv=None) -> int:
    rel = pd.read_csv(os.path.join(PIVOT_DIR, "p4_reliability.csv"))
    prox = pd.read_csv(os.path.join(PIVOT_DIR, "p4_variance_proxy.csv"))
    down4 = pd.read_csv(os.path.join(PIVOT_DIR, "p4_downstream.csv"))
    bio5 = pd.read_csv(os.path.join(PIVOT_DIR, "p5_biomarkers_hrf.csv"))
    dr5 = pd.read_csv(os.path.join(PIVOT_DIR, "p5_delta_r_hrf.csv"))
    px5 = pd.read_csv(os.path.join(PIVOT_DIR, "p5_pixel_hrf.csv"))
    au5 = pd.read_csv(os.path.join(PIVOT_DIR, "p5_downstream_hrf.csv"))

    dbio = dpx = ddr = None
    if os.path.exists(os.path.join(PIVOT_DIR, "p5_biomarkers_drive.csv")):
        dbio = pd.read_csv(os.path.join(PIVOT_DIR, "p5_biomarkers_drive.csv"))
        ddr = pd.read_csv(os.path.join(PIVOT_DIR, "p5_delta_r_drive.csv"))
        dpx = pd.read_csv(os.path.join(PIVOT_DIR, "p5_pixel_drive.csv"))

    runs = [("HRF ours (measure), lam 0.25", "runs/pivot/ft_hrf_seed0"),
            ("HRF ours, repeat (data seed 1)", "runs/pivot/ft_hrf_seed0_rep1"),
            ("HRF ours + clDice 0.5 in the base loss", "runs/pivot/ft_hrf_seed0_cld"),
            ("HRF CF-Loss-style, lam 1.0", "runs/pivot/ft_hrf_seed0_cfloss"),
            ("DRIVE ours (measure), lam 0.25", "runs/pivot/ft_drive_seed0"),
            ("DRIVE CF-Loss-style, lam 1.0", "runs/pivot/ft_drive_seed0_cfloss")]
    keys = ("base_val_dice", "best_dice", "epochs_run", "total_seconds",
            "mean_consist_frac", "term_density", "term_length", "term_fd")

    relcols = ["dataset", "biomarker", "r_single_mean_over_views", "r_view0",
               "r_pred_unperturbed", "r_mean", "d_mean", "d_mean_lo", "d_mean_hi",
               "r_median"]
    ftrows = []
    for label, p in runs:
        s = jload(os.path.join(p, "summary.json"))
        if s is None:
            continue
        lg = jload(os.path.join(p, "log.json"), {}).get("log", [])
        ftrows.append(dict(run=label, **{k: s.get(k) for k in keys},
                           final_val_dice=(lg[-1]["val_dice"] if lg else None)))
    ftsum = pd.DataFrame(ftrows)

    b = io.StringIO()
    W = b.write
    W(f"""# Pivot feasibility probes P4-P5

Follow-up to `results/pivot/PROBE_REPORT.md`.  Working thesis under test:
**per-image measurement reliability, not constant bias and not topology, is
what limits clinical validity.**  P4 asks whether test-time aggregation buys
reliability for free; P5 asks whether measurement-aware fine-tuning buys it.

Generated by `python -m src.pivot.make_report_p4p5`.  Code:
`src/pivot/p4_views.py`, `src/pivot/p4_tta.py`, `src/pivot/p5_finetune.py`,
`src/pivot/p5_eval.py`.  Outputs: `results/pivot/p4_*.csv`,
`results/pivot/p5_*.csv`, checkpoints under `runs/pivot/`.

Environment: Python 3.11.16 (`D:/Anaconda/envs/medical1`), torch 2.6.0+cu124
(GPU 1, RTX 3080), numpy 2.2.6, scipy 1.17.1, scikit-learn 1.9.0, pandas 3.0.5,
scikit-image 0.26.0, OpenCV 5.0.0, skan 0.13.1, PVBM 3.0.1.0.  `SEED = 0`
everywhere (splits, bootstraps, CV, fine-tuning).

---

## P4 -- test-time aggregation over anatomy-preserving views

### What was run

**P4a, biomarker-level aggregation over the Fig.4A perturbation views.**  The
existing tables `results/fig4a_stability_<ds>_none_per_view.csv` hold the four
primary biomarkers (both pipelines) for K = 8 anatomy-preserving *acquisition*
perturbations (`src/robust/perturb_views.py`: downsample-upsample, blur,
sharpen, gamma, vignette, colour gain, sensor noise, JPEG, small rigid
translation) of every test image, from the **baseline seed-0 segmenter**.
Coverage: HRF 30/30 test images, FIVES 60/200, DRIVE 20/20, CHASE_DB1 8/8.
Per image we form the view-mean and the view-median of each biomarker and
compare their reliability `r(B, B_GT)` against (i) a single view -- the mean
over the 8 views of the per-view `r` -- and (ii) view 0 alone, with a paired
image bootstrap (1000 resamples) of the difference.  The **unperturbed**
seed-0 prediction of `bio_master.csv` is carried along as the reference column
`r_pred_unperturbed`.

**P4b, probability-level dihedral TTA.**  The Fig.4A views are *degradations*,
so averaging them mostly undoes the damage the perturbation did.  The standard
strictly anatomy-preserving aggregation is the dihedral group D4 (4 rotations x
2 flips): transform, run the network, transform the probability map back,
average the 8 aligned maps, threshold once.  `src/pivot/p4_tta.py` writes this
to `runs/pivot/pred_hrf_tta8` with the `src/seg/infer.py` file conventions, and
its biomarkers go through exactly the same `compute_all(fd_rotations = 5,
disc from the fundus image)` path as `bio_master.csv`; the result is reported
as source `tta8` in the P5 tables below.

Provenance caveat for P4a: the per-view biomarkers were computed by
`src/robust/run_stability.py` with `compute_all(..., disc = None)` and the
default `fd_rotations = 25`, while `bio_master.csv` uses `fd_rotations = 5`
and a per-image optic disc.  The estimator is the same and only the number of
averaged rotations differs; the aggregation comparisons (`r_single` vs
`r_mean` / `r_median`) are all *within* the per-view table, so they are
unaffected.  `r_pred_unperturbed` is the one cross-provenance column and is
flagged as such.

### P4.1 Reliability of the view aggregate vs a single view (Spearman)

`d_mean` = `r_mean` - `r_single_mean_over_views`, with a paired image bootstrap
95 % CI.

{md(rel[rel["stat"] == "spearman"], relcols)}
### P4.1b The same, Pearson

{md(rel[rel["stat"] == "pearson"], relcols)}
### P4.2 Does the per-image spread across views predict the per-image |error|?

Spearman between the across-view standard deviation (and coefficient of
variation) and `|B_view-mean - B_GT|`.  This is the "free reliability proxy"
question: it needs no ground truth at inference time.

{md(prox)}
### P4.3 Downstream macro-AUC with view-aggregated features (HRF)

FIVES is **skipped**: the 60 FIVES images that have Fig.4A views are
`Glaucoma = 50, AMD = 5, Normal = 4, DR = 1`, which cannot support a 4-class
CV.  Extending the view generation to a class-balanced FIVES subset was not
worth the ~2 h of biomarker CPU it costs given the HRF outcome below.

{md(down4, r=4)}
### P4 verdict

**FAIL.**  Test-time aggregation does not buy the reliability the pivot needs.

* **The gains are real but an order of magnitude too small.**  On HRF the
  Spearman gain of the view-mean over a single view is +0.03 to +0.10
  (`FD_pvbm` +0.098 [0.001, 0.202], `total_length_pvbm` +0.086 [-0.021, 0.187],
  `tortuosity_skan` +0.040 [0.008, 0.086]); Pearson gains are +0.02 to +0.08.
  The pre-registered bar was **+0.1 on HRF** and only one biomarker's point
  estimate reaches it, with a CI whose lower end is 0.001.  On FIVES, where
  reliability is already 0.95-0.99, the gains are +0.006 to +0.013.  DRIVE and
  CHASE_DB1 are noisier (n = 20 / 8) and their CIs contain zero almost
  everywhere.
* **The comparison flatters aggregation, and the honest baseline kills it.**
  Every "single view" here is a *degraded* image, so averaging 8 of them mostly
  recovers what the degradation destroyed.  Against the **unperturbed**
  prediction the view-mean is a wash or worse: HRF `density` 0.674 -> 0.620,
  `total_length_skan` 0.301 -> 0.295, `tortuosity_pvbm` 0.723 -> 0.689; only
  `FD_pvbm` (0.368 -> 0.462) and `FD_skan` (0.268 -> 0.266, i.e. flat) are not
  losses.  FIVES is the same story (`total_length_pvbm` 0.984 -> 0.958).
* **Proper dihedral TTA, which *is* strictly anatomy-preserving, changes
  essentially nothing.**  D4 averaging of 8 aligned probability maps moves HRF
  Dice 0.8139 -> 0.8149 and clDice 0.8250 -> 0.8260, and the biomarker
  reliability by `d_r_pearson` = -0.046 to +0.032, every CI containing zero
  (table P5.2, source `tta8`).  The downstream macro-AUC moves 0.755 -> 0.770
  (logreg) and 0.687 -> 0.742 (GBDT), i.e. within noise of the original.
* **The variance proxy has moderate, biomarker-specific signal.**  The
  across-view spread predicts |error| at Spearman 0.46-0.48 for HRF FD,
  0.28-0.33 for HRF total length, 0.30-0.58 for FIVES -- but ~0 or negative for
  HRF density (-0.03) and for most of DRIVE / CHASE_DB1.  As a **free,
  label-free flag for "this FD measurement is unreliable"** it is worth
  keeping; as a correction it is not strong enough.

---

## P5 -- measurement-aware fine-tuning

### What was run

`src/pivot/p5_finetune.py` fine-tunes the existing HRF seed-0 U-Net
(`runs/seg/hrf/seed0/best.pt`, val Dice 0.8273) on the **HRF training split**
(13 images; val = the same 2 images as the original run; the 30 test images are
never touched) with

    L = BCE + soft Dice  +  lambda * C

and the P1-validated differentiable surrogates of `src/pivot/surrogates.py`
computed **on the training patch**, the GT side detached:

* **ours (`--loss-kind measure`)**: `C = |dd| + |dL| + |dFD|` as *relative*
  errors, where density is the FOV mean of `p`, length is the sum of the clDice
  soft skeleton, and FD is the box-count slope **on the soft skeleton with the
  resolution-adaptive ladder `2 .. min(H, W)/4`** -- the only FD surrogate that
  tracked the pipeline in P1.  **Tortuosity is excluded** (P1: rho -0.48..+0.33).
* **CF-Loss-style baseline (`--loss-kind cfloss`)**: `C = |dd| + |dFD|` only,
  FD taken on the **mask** with the **fixed `2..64` ladder**, i.e. the closest
  prior formulation.

Two extra HRF variants probe the two weakest points of the result:

* **repeat (`ft_measure_rep1`)** -- the identical recipe from the identical
  starting checkpoint with a different **data/augmentation seed** (`--seed 1
  --ckpt runs/seg/hrf/seed0/best.pt`), to see whether the reliability gain
  survives a re-run.  It is one repeat, not a proper multi-seed study.
* **clDice-preserving (`ft_measure_cldice`)** -- the same consistency loss on
  top of `BCE + Dice + 0.5 * soft-clDice`, to test whether the topology cost
  below is intrinsic to the consistency term or just a consequence of dropping
  topology from the objective while pushing three scalar surrogates.

Each term is a relative error so a single `lambda` scales the block; patches
with GT vessel fraction < 0.005 are dropped from `C` (FD of a near-empty patch
is meaningless).  `lambda` was chosen from a 5-batch probe at the starting
checkpoint so the consistency block is ~25 % of the loss at initialisation:
**`lambda = 0.25` (ours, 27-31 % -> 24 % after the probe) and `lambda = 1.0`
(CF-Loss-style, 17-30 %)**.  Adam, lr 1e-4 with poly(0.9) decay, 50 epochs x
100 iterations x batch 4 at patch 768 on the 1536-longest-side images, AMP on,
same augmentation and oversampling as the original training.

**Which checkpoint is evaluated, and why it matters.**  Validation Dice
**never improved** on either run (HRF 0.8273 -> 0.8115 at epoch 1 and 0.813 at
the end), so `best.pt` is the *untouched initial* checkpoint and a val-Dice
early-stopping rule would have rejected the fine-tune outright.  Everything
below therefore evaluates **`last.pt`** (the model after the full 50-epoch
schedule).  This is stated rather than hidden: the method costs val Dice.

Inference reuses `src/seg/infer.py` exactly (sliding window, patch 768, stride
384, Gaussian blend, no flips, threshold 0.5 inside the native FOV).  Sanity
check: re-running the *original* checkpoint through this path reproduces
`runs/seg/hrf/seed0/pred/mask` with **0.0 pixel disagreement** on all 30 test
images.  Biomarkers use `compute_all(fd_rotations = 5)` with the optic disc
detected from the fundus image alone, identical to `bio_master.csv`; sigma is
the pre-registered `results/gateA_biomarker_scales_train.csv`.

### P5.0 Fine-tuning runs

{md(ftsum, r=4)}
`mean_consist_frac` is the consistency block's share of the total loss averaged
over training; it starts near the 25 % target and falls as the term is
optimised away (HRF ours: 19 % over epoch 1 -> 7 % at epoch 50).  The raw
consistency term falls from ~0.44 at the starting checkpoint (5-batch probe)
and 0.344 averaged over epoch 1 to **0.113** at epoch 50 -- a 67-74 %
reduction in surrogate error on training patches.
The surrogates are therefore learnable -- the question is whether that transfers
to the real pipeline on held-out images.  `total_seconds` is not comparable
across rows: the repeat and clDice runs shared GPU 1 with another fine-tune,
so their wall-clock is roughly doubled.  `best_dice` equals `base_val_dice` in
every row, which is the "val Dice never improved" fact stated above.

### P5.1 HRF test (30 images): signed bias, standardised MAE, reliability

`bias_sigma` and `mae_sigma` are in units of the pre-registered training-split
sigma.  `orig` = `runs/seg/hrf/seed0/best.pt`, `tta8` = D4 TTA of the *same*
checkpoint (probe P4b), `ft_measure` / `ft_cfloss` = the two fine-tunes.

{md(bio5, r=4)}
### P5.2 Change in reliability vs the original model (paired image bootstrap, Pearson)

{md(dr5, r=4)}
### P5.3 Pixel metrics on the same 30 images (must not collapse)

{md(px5, r=4)}
### P5.4 Downstream macro-AUC, HRF test (30 images, 10 per class)

`gt_minus_this` is the attenuation vs the reference-mask ceiling;
`minus_orig` is the paired bootstrap of this source minus the original model.

{md(au5, r=4)}
""")

    if dbio is not None:
        W(f"""### P5.5 DRIVE (second dataset, 20 test images; DRIVE has no disease labels, so no downstream)

Bias / MAE / reliability:

{md(dbio, r=4)}
Change in reliability vs the original DRIVE seed-0 model (paired image bootstrap):

{md(ddr, r=4)}
Pixel metrics:

{md(dpx, r=4)}
""")

    W(f"""### P5 verdict

**PASS on the pre-registered criterion, in one configuration, with one large
side effect.**  The criterion was "reliability `r` rises by >= +0.1 on HRF and
the downstream AUC moves toward GT, without losing more than 0.01 clDice".
The **clDice-preserving variant** (`ft_measure_cldice`) meets all three:
`r` +0.13 to +0.17 on three biomarkers, macro-AUC 0.755 -> 0.807, clDice cost
**0.0038**.  The plain CE-Dice variant (`ft_measure`) meets the reliability and
AUC halves but spends 0.0198 clDice.  Both wreck tortuosity.

* **Reliability rises exactly where P1 said the surrogate is faithful, and the
  gain replicates.**  Pearson `r(B, B_GT)` on HRF test, change vs the original
  model (paired image bootstrap):

  | biomarker | ours (CE-Dice) | ours, repeat seed | ours + clDice | CF-Loss-style | D4 TTA |
  |---|---|---|---|---|---|
  | `FD_pvbm` | **+0.116 [0.037, 0.207]** | **+0.155 [0.078, 0.250]** | **+0.133 [0.066, 0.211]** | +0.071 [0.016, 0.140] | -0.001 [-0.020, 0.022] |
  | `FD_skan` | **+0.077 [0.011, 0.153]** | **+0.089 [0.009, 0.174]** | **+0.172 [0.045, 0.310]** | +0.002 [-0.058, 0.061] | -0.006 [-0.031, 0.020] |
  | `total_length_skan` | +0.034 [-0.025, 0.099] | +0.056 [-0.017, 0.128] | **+0.154 [0.009, 0.303]** | +0.013 [-0.040, 0.067] | -0.002 [-0.023, 0.021] |
  | `total_length_pvbm` | +0.010 [-0.057, 0.086] | -0.019 [-0.079, 0.054] | +0.065 [-0.030, 0.177] | +0.026 [-0.050, 0.100] | +0.027 [-0.025, 0.081] |
  | `density` | -0.085 [-0.165, -0.012] | -0.091 [-0.180, 0.001] | -0.077 [-0.155, -0.002] | -0.096 [-0.202, -0.002] | +0.013 [-0.017, 0.056] |

  The independent re-run from the same initialisation with a different
  data/augmentation seed lands within the first run's CI on every row and its
  pixel metrics match to 0.0008 (Dice 0.8077 vs 0.8071, clDice 0.8060 vs
  0.8052), so the FD effect is not a single-run accident.
* **Density reliability gets slightly but consistently *worse*** (-0.08 in all
  four fine-tunes, CI excluding zero in three of them) even though density is
  the surrogate with rho = 1.000 against the pipeline.  Its *bias* is what the
  loss removes (+0.431 sigma -> -0.09 / +0.08); the per-image ordering is not
  improved by making the mean right.  This is the P2 lesson reappearing inside
  the training objective and it should temper any "consistency loss improves
  measurement" claim to "improves the measurements whose error is dominated by
  a scale mismatch, i.e. FD and skeleton length".
* **Bias improves a lot, and inside the model.**  Best variant
  (`ft_measure_cldice`): `FD_skan` -1.627 -> **-0.626** sigma, `FD_pvbm`
  -0.954 -> -0.487, `total_length_skan` -1.789 -> **-0.706**,
  `total_length_pvbm` -3.096 -> -2.706, density +0.431 -> +0.083, with
  standardised MAE falling in step (`FD_skan` 1.729 -> 0.970,
  `total_length_skan` 1.915 -> 1.093).  P2 got comparable bias removal from a
  per-dataset constant that needs labelled images in every new domain; this
  travels with the weights.
* **Tortuosity is collateral damage, and in the clDice variant it is
  catastrophic.**  `tortuosity_pvbm` r 0.799 -> 0.630 (ours, -0.189 [-0.417,
  -0.031]) and -> **0.022** with clDice kept (**-0.762 [-1.061, -0.460]**), its
  bias going from -2.94 sigma to **+11.99 sigma**.  Tortuosity was deliberately
  excluded from the loss (P1: rho ~0), and the result is that nothing
  constrains it: the objective is free to reshape the mask into something whose
  arc/chord statistics are meaningless.  (PVBM's `TI = sum(arc)/sum(chord)`
  emits divide-by-zero warnings on these masks, so +11.99 sigma should be read
  as "the estimator broke", not as a calibrated magnitude.)  **Any
  biomarker-consistency paper must report the unconstrained biomarkers, not
  only the constrained ones.**
* **The topology cost is avoidable -- it came from dropping clDice, not from
  the consistency term.**  clDice on the 30 test images: original 0.8250,
  ours 0.8052 (**-0.0198**, over budget), ours + clDice-in-the-base-loss
  **0.8212 (-0.0038, within budget)**, CF-Loss-style 0.8147 (-0.0103), D4 TTA
  0.8260 (+0.0010).  And the clDice-preserving variant is *also* the best on
  reliability and bias, so this is not a trade -- it is strictly better.
* **Downstream moves toward GT, consistently, but never resolvably at
  n = 30.**  Logistic regression macro-AUC: GT 0.958, original 0.755, ours
  **0.820**, ours-repeat 0.805, ours+clDice 0.807, CF-Loss-style 0.758,
  D4 TTA 0.770.  Attenuation falls from +0.203 [0.080, 0.341] to +0.138
  [0.029, 0.267] (ours) -- about a third of the measurement-error gap closed --
  but the paired difference against the original is **+0.067 [-0.028, 0.173]**
  (ours), **+0.051 [-0.014, 0.122]** (repeat) and **+0.053 [-0.046, 0.166]**
  (clDice variant): the right sign three times over, never a CI that excludes
  zero.  GBDT is noisier still and disagrees on which variant is best
  (repeat 0.792, clDice variant 0.670).  **30 images at 10 per class cannot
  settle this.**
* **The CF-Loss-style baseline is separated by the box ladder, exactly as P1
  predicted.**  It gets a real but smaller `FD_pvbm` gain (+0.071 [0.016,
  0.140]), nothing on `FD_skan` (+0.002), and it **makes the FD bias markedly
  worse**: `FD_pvbm` -0.954 -> -1.291 sigma and `FD_skan` -1.627 -> -2.120,
  against -0.487 / -0.626 for ours.  The fixed `2..64` ladder does not span the
  pipeline's `2 .. min(H, W)/4` = `2..584` range on a 2336 x 3504 HRF image, so
  training against it drives the model to the wrong fractal scale.  Its
  downstream logreg AUC is unchanged (0.758 vs 0.755).
* **DRIVE does not replicate, and is too small to say more.**  20 test images,
  no disease labels.  Every `d_r` CI contains zero for ours (`FD_pvbm` +0.051
  [-0.078, 0.208], `FD_skan` -0.001, `total_length_skan` -0.048) and the clDice
  cost is the same as on HRF (0.8338 -> 0.8123, -0.0215).  Bias does improve
  (`total_length_skan` -1.050 -> -0.677, density +0.133 -> -0.299).  DRIVE's
  images are 565 x 584, where the fixed and adaptive FD ladders nearly coincide
  and where P1 already showed the naive ladder works -- so the mechanism that
  drives the HRF gain is largely absent.  This is a reason to test the next
  dataset at HRF/FIVES resolution, not at DRIVE resolution.

---

## What P4 and P5 together say about the pivot

1. **The reliability thesis survives and is now actionable.**  P3 said the
   bottleneck is per-image reliability, not bias.  P4 shows that no free,
   inference-time trick reaches it: neither averaging over acquisition
   perturbations (+0.03..+0.10 Spearman on HRF, and a *loss* against the clean
   prediction) nor strictly anatomy-preserving D4 TTA (-0.046..+0.032, every CI
   through zero).  P5 shows that **changing the training objective does** reach
   it -- +0.13 to +0.17 Pearson on HRF FD and skeleton length, replicated
   across two data seeds, with CIs excluding zero.  Reliability is a
   **training-time** property.  That is the strongest argument so far that D1
   is the load-bearing direction and that D2 / post-hoc repair are not.
2. **The effect is selective in a way that is itself the contribution.**  It
   works on FD and skeleton length, does nothing for density reliability (only
   its bias), and *destroys* tortuosity.  The pattern matches P1 exactly: the
   surrogate is faithful for density/length/FD-with-an-adaptive-ladder and
   useless for tortuosity, and the biomarkers whose per-image error is a scale
   mismatch are the ones that improve.  A paper can state and support:
   *biomarker-consistent training is the only lever that moves per-image
   reliability, it moves exactly the biomarkers P1 predicted, the
   resolution-adaptive FD ladder is what separates it from the CF-Loss-style
   prior, and unconstrained biomarkers degrade and must be reported.*
3. **Keep clDice in the base loss.**  The 0.0198 clDice cost that looked like
   the price of the method was an artefact of fine-tuning on plain CE-Dice;
   with `0.5 * soft-clDice` retained the cost is 0.0038 *and* the reliability
   and bias gains are larger.  There is no reliability/topology trade-off here,
   only a badly chosen base objective.
4. **The FD box ladder is a demonstrated design axis, not a tuning note.**  P1
   showed the fixed `2..64` ladder loses rank agreement on large images; P5
   shows that *training* against it drives `FD_skan` bias from -1.63 to -2.12
   sigma while the adaptive ladder drives it to -0.63.  Same loss family,
   opposite sign of effect, decided by one hyper-parameter that the prior work
   does not report.
5. **Statistical power is now the binding constraint, and the fix is known.**
   Every downstream CI is ~+/-0.10 wide because HRF test is 30 images at 10 per
   class; all three good variants improve the AUC and none of them resolves it.
   The next spend should be, in order: (a) a **class-balanced FIVES** fine-tune
   and evaluation -- 200 test images at 2048 x 2048, where the adaptive-ladder
   mechanism is strongest and P3 measured *zero* attenuation, which makes it a
   genuine falsification test rather than a confirmation; (b) 3 seeds x
   {{ours, ours+clDice, CF-Loss-style, baseline}} on HRF; (c) an ablation over
   the consistency terms (density-only / length-only / FD-only) to show the FD
   term is carrying the effect.
6. **Two by-products worth keeping.**  The across-view spread is a **label-free
   flag** for unreliable FD (Spearman 0.46-0.48 vs |error| on HRF, 0.30-0.58 on
   FIVES) -- it pairs with the P2 conformal intervals, which needed a few dozen
   labelled images per domain, and needs none.  And the fine-tune removes
   1-3 sigma of bias *inside the weights*, which is the transportable version of
   what P2's per-dataset constant did only in-domain.

## Reproduction

```
# P4a -- aggregation over the existing Fig.4A perturbation views (CPU, ~25 min)
python -m src.pivot.p4_views

# P4b -- D4 TTA of the baseline checkpoint (GPU 1, ~2 min + ~5 min CPU)
python -m src.pivot.p4_tta   --dataset hrf   --gpu 1 --tag tta8
python -m src.pivot.p4_tta   --dataset drive --gpu 1 --tag tta8
python -m src.pivot.p5_eval  bio --dataset hrf   --tag tta8 --procs 6
python -m src.pivot.p5_eval  bio --dataset drive --tag tta8 --procs 6

# P5 -- the fine-tunes (GPU 1; HRF ~22 / ~16 min, DRIVE ~19 / ~15 min)
python -m src.pivot.p5_finetune --dataset hrf --gpu 1 --loss-kind measure --lam 0.25 \\
    --epochs 50 --out runs/pivot/ft_hrf_seed0
python -m src.pivot.p5_finetune --dataset hrf --gpu 1 --loss-kind measure --lam 0.25 \\
    --epochs 50 --seed 1 --ckpt runs/seg/hrf/seed0/best.pt \\
    --out runs/pivot/ft_hrf_seed0_rep1          # same init, different data seed
python -m src.pivot.p5_finetune --dataset hrf --gpu 1 --loss-kind cfloss --lam 1.0 \\
    --epochs 50 --out runs/pivot/ft_hrf_seed0_cfloss
python -m src.pivot.p5_finetune --dataset drive --gpu 1 --loss-kind measure --lam 0.25 \\
    --epochs 50 --out runs/pivot/ft_drive_seed0
python -m src.pivot.p5_finetune --dataset drive --gpu 1 --loss-kind cfloss --lam 1.0 \\
    --epochs 50 --out runs/pivot/ft_drive_seed0_cfloss

# inference + biomarkers + report   (repeat with --dataset drive)
python -m src.pivot.p5_eval infer  --dataset hrf --gpu 1 --tag orig            --ckpt runs/seg/hrf/seed0/best.pt
python -m src.pivot.p5_eval infer  --dataset hrf --gpu 1 --tag ft_measure      --ckpt runs/pivot/ft_hrf_seed0/last.pt
python -m src.pivot.p5_eval infer  --dataset hrf --gpu 1 --tag ft_measure_rep1 --ckpt runs/pivot/ft_hrf_seed0_rep1/last.pt
python -m src.pivot.p5_eval infer  --dataset hrf --gpu 1 --tag ft_cfloss       --ckpt runs/pivot/ft_hrf_seed0_cfloss/last.pt
python -m src.pivot.p5_eval bio    --dataset hrf --tag ft_measure      --procs 6
python -m src.pivot.p5_eval bio    --dataset hrf --tag ft_measure_rep1 --procs 6
python -m src.pivot.p5_eval bio    --dataset hrf --tag ft_cfloss       --procs 6
python -m src.pivot.p5_eval report --dataset hrf   --tags ft_measure,ft_measure_rep1,ft_cfloss,tta8
python -m src.pivot.p5_eval report --dataset drive --tags ft_measure,ft_cfloss,tta8
python -m src.pivot.make_report_p4p5
```

Wall-clock for the whole P4+P5 round: ~3 h, of which ~40 min GPU (GPU 1 only;
GPU 0 was left to the running Fig.4 job) and ~35 min of 6-process biomarker CPU.
""")

    os.makedirs(PIVOT_DIR, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(b.getvalue())
    print("wrote", OUT, len(b.getvalue()), "chars")
    return 0


if __name__ == "__main__":
    sys.exit(main())
